config/routes.rb
Rails.application.routes.draw do
  resources :todos
  get "pages/home"
  get "pages/me", to: "pages#me", as: :me

  # Path Configuration
  namespace :configurations, defaults: {format: :json} do
    get "ios/v1" => "ios#v1"
    get "android/v1" => "android#v1"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/configurations/ios_controller.rb
module Configurations
  class IosController < ApplicationController
    def v1
      render json: {
        settings: {},
        rules: [
          {
            patterns: [
              ".*"
            ],
            properties: {
              context: "default",
              pull_to_refresh_enabled: true
            }
          },
          {
            patterns: [
              "/new$"
            ],
            properties: {
              context: "modal", 
              pull_to_refresh_enabled: false
            }
          },
          {
            patterns: [
              "/pages/me$"
            ],
            properties: {
              context: "default",
              presentation: "replace",
              hide_navbar: true,
              hide_tabs: true
            }
          }
        ]
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def me
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo, notice: "Todo was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      redirect_to @todo, notice: "Todo was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy!
    redirect_to todos_path, notice: "Todo was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.expect(todo: [ :title, :status, :description, :ends_at ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_header.html.erb
<nav class="w-full bg-purple-600">
    <!-- Inner container for centered content -->
    <div class="container mx-auto px-4">
        <div class="flex justify-between items-center h-16">
            <!-- Left side - Home link -->
            <div>
              <%= link_to "Hotwire Native", root_path, class: "text-white text-lg font-semibold hover:text-purple-200" %>
            </div>

            <!-- Right side - Navigation links -->
            <div class="flex space-x-6">
                <%= link_to "ToDos", todos_path, class: "text-white hover:text-purple-200" %>
                <%= link_to "Me", me_path, class: "text-white hover:text-purple-200" %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Home" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/pages/me.html.erb
<%= content_for :title, "Me" %>

<div>
  <h1 class="font-bold text-4xl">Pages#me</h1>
  <p>Find me in app/views/pages/me.html.erb</p>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, class: "contents") do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.checkbox :status, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ends_at %>
    <%= form.datetime_field :ends_at, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= todo.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= todo.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= todo.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ends at:</strong>
    <%= todo.ends_at %>
  </p>

</div>

app/views/todos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Show this todo", @todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Todos" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Todos</h1>
    <%= link_to "New todo", new_todo_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="todos" class="min-w-full">
    <% @todos.each do |todo| %>
      <%= render todo %>
      <p>
        <%= link_to "Show this todo", todo, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to "Edit this todo", edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to todos", todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this todo", @todo, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>